# Form implementation generated from reading ui file 'dialog_help.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Dialog_Help(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(586, 482)
        Dialog.setStyleSheet("background-color: rgb(228,228,228);\n"
"color: rgb(0, 0, 0);")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label.setIndent(0)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Câu hỏi thường gặp"))
        self.label.setText(_translate("Dialog", "Xem camera trực tiếp ở đâu?\n"
"\n"
"Chúng tôi biết bạn đang muốn xem camera trực tiếp, chứ không phải là hình\n"
"ảnh được cắt từ camera. Nhưng rất tiếc, do Sở giao thông vận tải chỉ cung cấp\n"
"hình ảnh mỗi 6-12 giây làm mới một lần cho người dân.\n"
"Vì vậy, hiện tại chỉ có rất ít khu vực cung cấp camera giao thông trực tiếp cho\n"
"người dân, cho nên việc cung cấp camera trực tiếp còn rất nhiều hạn chế và\n"
"thẩm quyền bạn nhé\n"
"\n"
"Sao hình ảnh camera chất lượng kém?\n"
"\n"
"Chúng tôi đã tải ảnh và chỉnh sửa chất lượng gốc (tốt nhất) về phần mềm này,\n"
"vì vậy hình ảnh chất lượng kém là do camera tại đường đó đã quá cũ, bụi bẩn\n"
"hoặc do Sở giao thông vận tải chỉ cung cấp chất lượng thấp đến người dân.\n"
"\n"
"\n"
"Liên hệ chúng tôi \n"
"\n"
"Nếu bạn có bất kỳ câu hỏi hay đề xuất nào hoặc cần hỗ trợ, đừng ngần ngại \n"
"liên hệ qua minhlapp2@gmail.com\n"
""))
